### PR TITLE
Several improvements for checking that YAML files are sane

### PR DESCRIPTION
**Pull request by FrancescAlted**
This is a work in progress PR for improvements that @sigbjorn asked in the [gitter channel](https://gitter.im/statkraft).  Open to comments here.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Thanks @sigbjorn.  So, that means that when the user wants to override a parameter in a region, she must be forced to specify the complete set of {gamma_snow, priestley_taylor, kirchner, actual_evapotranspiration, skaugen, hbv_snow}.  Is that correct?  If so, I will try to come up with a new PR for that.

**Comment by skavhaug** [comment]
2 cents from the side line: That does not sound correct to me.

**Comment by skavhaug** [comment]
One method stack defines one subset of the possible methods. So having to specify both skaugen and hbv_snow in order to override is not optimal. I would say that overriding all the parameters for the method stack in question could be a ok compromize.

**Comment by FrancescAlted** [comment]
Yes, I noticed that.  For example, in model.yaml in tests there is hbv_snow, but not skaugen.  So SHyFT should be aware of the different method stacks that can be possible (and hence all the allowed method subsets).  Is this info available somewhere?

**Comment by FrancescAlted** [comment]
Hmm, before proceeding in this one I think it would be nice to have a meeting so that this is clarified.  If we cannot hangout because of lack of sync in schedule, perhaps using gitter would be a good alternative.  I will start a thread there.

**Comment by jfburkhart** [comment]
Hi, 2 cents from here also...  "As a user I would like to define individual catchment parameters to be overwritten in a simple, clear manner without defining all other parameters". If I recall, we define the  'default' parameters to use in the model.yaml, then these may be overwritten individually. Is this not the intent? @yisak do you have an opinion here?

**Pull request merged**
