### PR TITLE
Support for CMake (ported to Python 3)

### PR DESCRIPTION
**Pull request by FrancescAlted**
Here it is another PR for CMake support.  This time the support has been ported to Python 3 (no support for Python2 is here).  Although cmake seems to work just fine in my local box, I am still having problems with TravisCI of this style:

```
kirchner_test.cpp:(.text+0x1d4f): undefined reference to `CxxTest::TestTracker::tracker()'

kirchner_test.cpp:(.text+0x1d9b): undefined reference to `CxxTest::TestTracker::tracker()'

kirchner_test.cpp:(.text+0x1de7): undefined reference to `CxxTest::TestTracker::tracker()'

kirchner_test.cpp:(.text+0x1e28): undefined reference to `CxxTest::TestTracker::tracker()'

CMakeFiles/test_shyft.dir/kirchner_test.cpp.o: In function `kirchner_test::test_solve_from_zero_q()':

kirchner_test.cpp:(.text+0x2126): undefined reference to `CxxTest::TestTracker::tracker()'

CMakeFiles/test_shyft.dir/kirchner_test.cpp.o:kirchner_test.cpp:(.text+0x2173): more undefined references to `CxxTest::TestTracker::tracker()' follow
```

Tomorrow I am going to continue with that, but if someone is seeing this I would appreciate any feedback.  The full Travis log is here:

https://travis-ci.org/FrancescAlted/shyft/jobs/85554087

### CODE REVIEW

**Comment by sigbjorn** [comment]
Ok, - I could try to see if this could work on a blank ubuntu/arch linux/fedora box, 
  and see if are able to get a working version that work.

# Regarding armadillo, and how we use armadillo, 
  I think we can improve on that part.
   Currently we are using header-only/blas-lapack.  

   armadillo can autoconfigure to whatever blas/lapack drop-in that is on the compiling server,
   then we just add library for libarmadillo (takes care of bridging the gap to the underlying libraries).

I am a bit busy these two days, but during weekend there is a chance I could see if it could work.

I am also a bit curious about how we can create/ or evolve this into a buildserver that do incremental builds (instead of massive download/compile etc..etc..).

**Comment by FrancescAlted** [comment]
Well, I discovered that the tests only need a tiny part of boost (boost_filesystem and boost_system), so compiling only these 2 libs is a breeze compared with the whole thing.  Currently, the time it takes to compile everything (ShyFT + dependencies) is slightly less than 10 min (using 2 cores on TravisCI), which is not bad at all.

And yes, I am not familiar with armadillo, so currently I am just using its headers, not as a library, but it would be nice to learn to use it as an interface to lower-level blas and lapack.

The thing that is taking me most of my time is to understand why the TravisCI has some linking problems, when my local laptop is good.  Tomorrow will put more time on debugging this.

**Comment by FrancescAlted** [comment]
After a good debugging session, I have just nailed down the problem (see 47f05d6).  With that, the TravisCI job compiles and run the tests (both C++ and Python) just fine.  Well, there is just one hiccup:

```
$ nosetests ..

.................................S...........S..........S..E.....

======================================================================

ERROR: test_missing_and_existing_locations (shyft.tests.test_yaml_geo_location_repository.TestYamlGeoLocationRepository)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/FrancescAlted/shyft/shyft/tests/test_yaml_geo_location_repository.py", line 34, in test_missing_and_existing_locations

    with open(path.join(self._test_state_directory,"pt_locations-epsg_32632.yml"),"w") as f:

FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/FrancescAlted/shyft/shyft/tests/state_tmp/pt_locations-epsg_32632.yml'

----------------------------------------------------------------------

Ran 65 tests in 47.542s

FAILED (SKIP=3, errors=1)
```

For reference, the full log is here:

https://travis-ci.org/FrancescAlted/shyft/builds/89634197

My experience is that this test sometimes works well, but others don't, so we should try to make it reproducible.  I'll open a ticket on that later on.

**Comment by skavhaug** [comment]
I think this is a problem with unit tests not being run in any particular
order?

Ola Skavhaug, PhD
Founder, Expert Analytics AS

**Comment by FrancescAlted** [comment]
Maybe, but if that is the case, then we should avoid that by using several techniques.  See:

http://stackoverflow.com/questions/16364433/execution-order-on-python-unittest

**Comment by skavhaug** [comment]
I totally agree.

**Comment by FrancescAlted** [comment]
This PR is full working now and meant to the merged.  Just a few more info on what this CMake support brings on the table:

* Automatically download and compile dependencies and compile SHyFT itself.

* The dependencies are stored in its own directory and are cached between runs (so that they don't have to be downloaded every time).

* The user can select a specific version of a dependency via `DEPLIB_VERSION=X.Y.Z` (e.g. `cmake -DBOOST_VERSION=1.60.1`).  This dependency will be downloaded automatically and compiled (if necessary).

* User doesn't need root privileges.  She can keep the binaries within the sources and use them from everywhere by just keeping 2 environment variables: LD_LIBRARY_PATH and SHYFT_SOURCES (maybe this can even be reduced to just the latter).

* This should work on both Linux (tested) and Mac OSX (not tested).  Windows is possible, but not tested yet (but won't work for sure).

* Continuous Integration support via TravisCI is here (currently using Ubuntu 14.04).

* CMake support here is completely independent of the existing building scripts and do not mess with them in any way.

## Future work

* When/if this PR is accepted, one can think make setup.py aware of cmake and use it for an even smoother (and standard) installation procedure.

* By using TravisCI one can think on creating binaries (conda bundles, Python wheels) on a nightly basis and uploading them into a binary repository.

* Windows support can be added to CMake (can take some time though).

**Comment by sigbjorn** [comment]
.. i do a test locally now, using ubuntu 15.10, ..

**Comment by FrancescAlted** [comment]
yay!

**Pull request merged**
