### PR TITLE
fix of save_calibrated_state per #368

### PR DESCRIPTION
**Pull request by jfburkhart**
Quick fix using github directly, may want to run through tests.

### CODE REVIEW

**Comment by sigbjorn** [comment]
note that build failed just because the open-dap test. I restarted build, and will merge if it failes due to this flaky test.

**Comment by sigbjorn** [comment]
hmm. no, it's a real failing test test_extract_conversion_factors_from_string
will check that one.

**Comment by jfburkhart** [comment]
ok. I'll take a look.

**Comment by felixmatt** [comment]
Looks like the tests failing are not related to this PR?!

**Comment by sigbjorn** [comment]
not related to the PR, it's cftime vs. netcdftime changes. I merge this, and then start fixing the failing tests.

**Pull request merged**
