### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by FrancescAlted**
This is a *preliminary* PR that uses CMake for:

* Download the sources for armadillo and dlib (during the tests, I discovered that boost is not necessary, Sigbjørn?).  There are defaults for versions, but users are able to specify a version from command line too.

* Compile the extensions and copy them in the `shyft/api` directory.

After applying the patch, the way to use it is super-easy:

```
$ cd your-shyft-source
$ mkdir build; cd build
$ cmake ..
$ nosetests ..
...
----------------------------------------------------------------------
Ran 3 tests in 4.068s

OK
```
And that's all, you don't need to bother installing dependencies other that blas and lapack (but installing numpy should typically take care of this).

Also, the SWIG sources are in the repo now.  This has a couple of advantages:

* The SWIG generation step (very costly in terms of CPU and memory) is avoided

* SWIG is not a requirement for CI

* Because the source code for the SWIG wrappers are available in the repo, in the future we will be able to use [coverage](https://pypi.python.org/pypi/coverage) or tools like [asv](https://github.com/spacetelescope/asv/).

This will allow to start using TravisCI or other Continuous Integration platforms and the only required step will be compiling the extensions via cmake.  In next commits, I will provide scripts for TravisCI (and possibly AppVeyor too).

For now, this works on a Unix machine (Ubuntu), but the idea is to make it compatible with OSX and Windows as well (CMake should enable us doing this portability easily enough).

### CODE REVIEW

**Comment by jfburkhart** [comment]
Spoke with Francesc on this. There are a few outstanding matters:

- inclusion of boost (we need to understand where the dependency comes in because we get green lights on the tests without it)
- better inclusion of SWIG extensions (.cxx files are missing now)
- possibility for user to set versions of dlib and armadillo dependencies

We will not merge PR#20 now, but it is here for reference.

**Comment by sigbjorn** [comment]
Ok, I have some comments, that could influence how a follow up PR is created:

a)  We do not want the huge swig-generated files into the repository.
The basic idea of shyft (src) is that it should be minimal, once we get in generated files, this gets huge..


b) install run/swig is by far the easiest dependency we have had so far.
 It works on *all* platforms we have tried, consistently , ubuntu,arch, fedora, even windows!


c) we now use make -j 4 for the build_api.sh, so the build-time is constant


d) the tests of shyft is in three parts:

    1. the core c++ test, and these tests does not use swig, so they compile/run  fast.
       during development of c++, these are the tests that we run.
       The quality of shyft rely entirely on the quality and coverage these tests provides.
       Lessons leared: don't try to expose something to api/through swig before tested in c++ .

    2. the test/python tests, 
         this is minmal python-api tests (require shyft python, thus swig)
         to verify that the the *api* exposed to python through swig works as expected.

    3. recently added python tests and examples added in shyft/test/*
       these aim to test the *python* parts, i.e. repositories and orchestrators.
       They need a working core (covered through tests) 
       and  a working shyft python api (covered through tests in 2. above)
       
e) dependencies
  The c++ build description on the github wiki, - including dependencies.
   Yes, we use boost, armadillo, dlib. The dependencies are for real.
    boost is sometimes installed in system directories, so include paths,libs etc 
   comes for free. When it comes to version of boost etc, -I recommend what I have tested.

**Comment by FrancescAlted** [comment]
Ok, so I made quite a progress testing cmake in combination with [TravisCI](https://travis-ci.org/FrancescAlted/shyft/builds).  By doing this we can be reasonably sure that the cmake is behaving well in a clean machine (i.e. with no existing boost or other dependencies).  And indeed, this setup shown that boost was required by the Python tests too.  The other advantage is that we can configure Shyft to run the tests automatically per every commit or PR, which will be very useful before accepting patches without the need to run the tests manually.  TravisCI support is partial in that only the Python tests run currently, and only for Ubuntu Linux, but OSX (should be easy) and Windows (could require more effort and using something like [AppVeyor](http://www.appveyor.com/)) could be added later on.

I am still having problems with the [compilation process crashing on TravisCI](https://travis-ci.org/FrancescAlted/shyft/jobs/85741010), although fortunately Python 2.6 environment seems to require less resources and [normally succeeds, bar Python 2.7 specific idioms](https://travis-ci.org/FrancescAlted/shyft/jobs/85741008).  I think the problem is that TravisCI legacy infrastructure only provides machines with 3 GB which is probably putting problems to g++ (I have seen 1.6 GB peaks in my laptop, only for the *compiler process*).  I think moving to the [new TravisCI infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade), which provides 4 GB per machine would be enough.  That will be the next step.

Finally, this PR still needs the sources that are SWIG-generated to be in the repo, but as @sigbjorn does not like that, I plan to add the SWIG generation to the CMake configuration too.  That will add a considerable amount of time (and memory) to every CI run, and possible being unable to use `code coverage` libraries, but let's try this and see.

**Comment by sigbjorn** [comment]
Great that you work on this as well, 

About checking in the swig generated sources:

 
  *    No, I think we should not do that, at least not into the shyft repository

  Could it be easier if we in stead we could checkin (or make available) prebuilt binaries for python work(win&ubuntu) ?


   The dependencies could be as few as zero (if we provide needed blas/lapack/boost,and crt, for the windows version)

  This could then easiliy support python work related PR. 

     (after all there will be few people that could contribute to the C++ part).



Buildsystem:

I think we should aim for a build server system that supports 'the image' that we need.


This will be much faster than any other alternative, and will rule out typical 'one-time' tasks,
and we also get incremental builds where only needed compiles are performed.

Taking the complete build time from scratch:


*  tanking down the compilers, boost, dlib,armadillo, cxxtest, swig 


*  not to mention the correct supported version version of python stack (anaconda), 

  + including packages needed by orch/repos/test/demo/ui.

  This takes way to much time (if we aim for something in spit-seconds) ..


So, if we want to have a fast CI (for the purose of PR), - then I believe we need to do some work to figure how to find or make a system that can do that for us.


If  we just want to have something the provides nightly builds, then build time does not matter.

For me, and other working on SHyFT, we have the fastest possible build system locally, - but it would be nice to have an official build, test and package system, that do some work and give feedback while we sleep.



As a minimum it should support latest windows and linux (ubuntu,fedora,arch).

Also I think we should keep at 'head' of the component versions we use, 
I can't se any value (at this stage ) to support ancient versions of gcc, python (soon 3.x now) boost, mswin, swig, etc.

At statkraft, we do have a windows-type (team-city) buildserver, so we could setup builds that push results/packages out from there.

**Pull request closed without merging**
