### PR TITLE
Migrated existing sphinx docs in ENKI

### PR DESCRIPTION
**Pull request by FrancescAlted**
These should make a good start for SHyFT docs.

Having the documentation in the same repo than sources makes submitting more consistent PRs because they can include improvements in docs in the same PR, making the revision process much easier.

### CODE REVIEW

**Comment by jfburkhart** [comment]
This LGTM. We (Francesc and I) discussed the importance of documentation existing within the repository. Migrating the sphinx doc now will promote better conventions and documentation.

With this, we should also **improve our efforts regarding docstrings**.

**Comment by skavhaug** [comment]
Is there a reason we go for rst and not md?

Except for that, I agree that the source needs to be documented in source,
i.e., focus on writing proper doc strings in Python, and make an effort in
exposing the C++ doc as docstrings in Python.

Ola Skavhaug, PhD
Founder, Expert Analytics AS

**Comment by jfburkhart** [comment]
Let's pull this in now, and we can fix the documentation from the repo. At least the glaring issues.

**Comment by skavhaug** [comment]
After discussion with @jfburkhart, LTGM as long as we update the content in a separate PR soon.

**Pull request merged**
